
/******************************************************************************/
/**
* \file       imum.h
* \brief      
* \details    
*             
* \author     Hongming.ZHENGH
* \date       09/05/2023
* \par        History:
* 
\verbatim
  Version     Author                    Date            Desc   
  1.0         Hongming.ZHENGH           09/05/2023
\endverbatim  
*
*/
/**************** (C) Copyright 2023 Magneti Marelli Guangzhou ****************/

/*=======[I N C L U D E S]====================================================*/
#include "asm330lhh_cfg.h"

/*=======[M A C R O S]========================================================*/
	
/*=======[T Y P E   D E F I N I T I O N S]====================================*/

/*=======[E X T E R N A L   D A T A]==========================================*/

/*=======[I N T E R N A L   D A T A]==========================================*/

/* control register initial config */
const uint16 asm330lhh_InitialDeviceCtrlRegCfg[ASM330LHH_CTRL_REG_NUM] =
{
        ASM330LHH_PIN_CTRL_ADDR |
        ASM330LHH_PIN_CTRL_BIT_SDO_PU_DISABLE,
        
        ASM330LHH_FIFO_CTRL1_ADDR |
        ASM330LHH_FIFO_CTRL1_BIT_WTM_bit7_0_DEFAULT,
        
        ASM330LHH_FIFO_CTRL2_ADDR |
        ASM330LHH_FIFO_CTRL2_BIT_STOP_ON_WTM_DISABLE |
        ASM330LHH_FIFO_CTRL2_BIT_ODRCHG_DISABLE |
        ASM330LHH_FIFO_CTRL2_BIT_WTM_bit8_DEFAULT,
        
        ASM330LHH_FIFO_CTRL3_ADDR |
        ASM330LHH_FIFO_CTRL3_BIT_BDR_GY_104_HZ |
        ASM330LHH_FIFO_CTRL3_BIT_BDR_XL_104_HZ,
        
        ASM330LHH_FIFO_CTRL4_ADDR |
        ASM330LHH_FIFO_CTRL4_BIT_DEC_TS_BATCH_NotBatched |
        ASM330LHH_FIFO_CTRL4_BIT_ODR_T_BATCH_NotBatched |
        ASM330LHH_FIFO_CTRL4_BIT_FIFO_MODE_Continuous_mode,

        ASM330LHH_COUNTER_BDR_REG1_ADDR |
        ASM330LHH_COUNTER_BDR_REG1_BIT_Dataready_Latched_mode |
        ASM330LHH_COUNTER_BDR_REG1_BIT_RST_COUNTER_BDR_DISABLE |
        ASM330LHH_COUNTER_BDR_REG1_BIT_TRIG_COUNTER_BDR_XL |
        ASM330LHH_COUNTER_BDR_REG1_BIT_CNT_BDR_TH_9_8_DEFAULT,

        ASM330LHH_COUNTER_BDR_REG2_ADDR |
        ASM330LHH_COUNTER_BDR_REG2_BIT_CNT_BDR_TH_7_0_DEFAULT,

        ASM330LHH_INT1_CTRL_ADDR |
        ASM330LHH_INT1_CTRL_BIT_DEN_DRDY_flag_DISABLE |
        ASM330LHH_INT1_CTRL_BIT_INT1_CNT_BDR_DISABLE |
        ASM330LHH_INT1_CTRL_BIT_INT1_FIFO_FULL_DISABLE |
        ASM330LHH_INT1_CTRL_BIT_INT1_FIFO_OVR_DISABLE |
        ASM330LHH_INT1_CTRL_BIT_INT1_FIFO_TH_DISABLE |
        ASM330LHH_INT1_CTRL_BIT_INT1_BOOT_DISABLE |
        ASM330LHH_INT1_CTRL_BIT_INT1_DRDY_G_DISABLE |
        ASM330LHH_INT1_CTRL_BIT_INT1_DRDY_XL_ENABLE,

        ASM330LHH_INT2_CTRL_ADDR |
        ASM330LHH_INT2_CTRL_BIT_INT2_CNT_BDR_DISABLE |
        ASM330LHH_INT2_CTRL_BIT_INT2_FIFO_FULL_DISABLE |
        ASM330LHH_INT2_CTRL_BIT_INT2_FIFO_OVR_DISABLE |
        ASM330LHH_INT2_CTRL_BIT_INT_FIFO_TH_DISABLE |
        ASM330LHH_INT2_CTRL_BIT_INT2_DRDY_TEMP_DISABLE |
        ASM330LHH_INT2_CTRL_BIT_INT2_DRDY_G_ENABLE |
        ASM330LHH_INT2_CTRL_BIT_INT2_DRDY_XL_DISABLE,

        ASM330LHH_CTRL1_XL_ADDR |
        ASM330LHH_CTRL1_XL_BIT_ODR_XL_208_Hz |
        ASM330LHH_CTRL1_XL_BIT_FS_XL_2g |
        ASM330LHH_CTRL1_XL_BIT_LPF2_XL_DISABLE,

        ASM330LHH_CTRL2_G_ADDR |
        ASM330LHH_CTRL2_G_BIT_ODR_G_208_Hz |
        ASM330LHH_CTRL2_G_BIT_FS_G_250_dps |
        ASM330LHH_CTRL2_G_BIT_FS_125_THROUGH_FS_G |
        ASM330LHH_CTRL2_G_BIT_FS_4000_THROUGH_FS_G_FS_125,

        ASM330LHH_CTRL3_C_ADDR |
        ASM330LHH_CTRL3_C_BIT_BOOT_NormalMode |
        ASM330LHH_CTRL3_C_BIT_BDU_ContinuousUpdate |
        ASM330LHH_CTRL3_C_BIT_H_LACTIVE_High |
        ASM330LHH_CTRL3_C_BIT_PP_OD_PushPull_Mode |
        ASM330LHH_CTRL3_C_BIT_SIM_4_Wire |
        ASM330LHH_CTRL3_C_BIT_IF_INC_ENABLE |
        ASM330LHH_CTRL3_C_BIT_SW_RESET_NormalMode,

        ASM330LHH_CTRL4_C_ADDR |
        ASM330LHH_CTRL4_C_BIT_SLEEP_G_DISABLE |
        ASM330LHH_CTRL4_C_BIT_INT2_on_INT1_DISABLE |
        ASM330LHH_CTRL4_C_BIT_DRDY_MASK_DISABLE |
        ASM330LHH_CTRL4_C_BIT_I2C_DISABLE |
        ASM330LHH_CTRL4_C_BIT_I2C_LPF1_SEL_G_DISABLE,

        ASM330LHH_CTRL5_C_ADDR |
        ASM330LHH_CTRL5_C_BIT_ROUNDING_NO |
        ASM330LHH_CTRL5_C_BIT_ST_G_NormalMode |
        ASM330LHH_CTRL5_C_BIT_ST_XL_NormalMode,

        ASM330LHH_CTRL6_C_ADDR |
        ASM330LHH_CTRL6_C_BIT_TRIG_EN_DISABLE |
        ASM330LHH_CTRL6_C_BIT_LVL1_EN_DISABLE |
        ASM330LHH_CTRL6_C_BIT_LVL2_EN_DISABLE |
        ASM330LHH_CTRL6_C_BIT_USR_OFF_W_2_10 |
        ASM330LHH_CTRL6_C_BIT_FTYPE_DEFAULT,

        ASM330LHH_CTRL7_G_ADDR |
        ASM330LHH_CTRL7_G_BIT_HP_EN_G_DISABLE |
        ASM330LHH_CTRL7_G_BIT_HPM_G_16mHz |
        ASM330LHH_CTRL7_G_BIT_USR_OFF_ON_OUT_Bypassed,

        ASM330LHH_CTRL8_XL_ADDR |
        ASM330LHH_CTRL8_XL_BIT_HPCF_XL_ODR_4 |
        ASM330LHH_CTRL8_XL_BIT_HP_REF_MODE_XL_DISABLE |
        ASM330LHH_CTRL8_XL_BIT_FASTSETTL_MODE_XL_DISABLE |
        ASM330LHH_CTRL8_XL_BIT_HP_SLOPE_XL_EN_LOW_PASS |
        ASM330LHH_CTRL8_XL_BIT_LOW_PASS_ON_6D_ODR_2_LOW_PASS_FILTERED,

        ASM330LHH_CTRL9_XL_ADDR |
        ASM330LHH_CTRL9_XL_BIT_DEN_X_STORED_IN_X_axis_LSB |
        ASM330LHH_CTRL9_XL_BIT_DEN_Y_STORED_IN_Y_axis_LSB |
        ASM330LHH_CTRL9_XL_BIT_DEN_Z_STORED_IN_Z_axis_LSB |
        ASM330LHH_CTRL9_XL_BIT_DEN_XL_G_Stamped_In_The_Gyroscope_Axis |
        ASM330LHH_CTRL9_XL_BIT_DEN_XL_EN_DISABLE |
        ASM330LHH_CTRL9_XL_BIT_DEN_LH_ACTIVE_LOW |
        ASM330LHH_CTRL9_XL_BIT_DEVICE_CONF_DEFAULT,

        ASM330LHH_CTRL10_C_ADDR |
        ASM330LHH_CTRL10_C_BIT_TIMESTAMP_EN_ENABLE,

        ASM330LHH_INT_CFG0_ADDR |
        ASM330LHH_INT_CFG0_BIT_INT_CLR_ON_READ_DISABLE |
        ASM330LHH_INT_CFG0_BIT_SLEEP_STATUS_ON_INT_CHNAGE_NOTIFY |
        ASM330LHH_INT_CFG0_BIT_SLOPE_FDS_SLOPE_FILTER_APPLIED |
        ASM330LHH_INT_CFG0_BIT_LIR_NOT_LATCHED,

        ASM330LHH_INT_CFG1_ADDR |
        ASM330LHH_INT_CFG1_BIT_INTERRUPTS_DISABLE |
        ASM330LHH_INT_CFG1_BIT_INACT_EN_A_AND_G_NOT_CHNAGE,

        ASM330LHH_THS_6D_ADDR |
        ASM330LHH_THS_6D_BIT_D4D_EN_DISABLE |
        ASM330LHH_THS_6D_BIT_SIXD_THS_80_DEGRESS,

        ASM330LHH_WAKE_UP_THS_ADDR |
        ASM330LHH_WAKE_UP_THS_BIT_DISABLE |
        ASM330LHH_WAKE_UP_THS_BITS_WK_THS_DEFAULT,

        ASM330LHH_WAKE_UP_DUR_ADDR |
        ASM330LHH_WAKE_UP_DUR_BIT_FF_DUR5_DEFAULT |
        ASM330LHH_WAKE_UP_DUR_BIT_WAKE_DUR_DEFAULT |
        ASM330LHH_WAKE_UP_DUR_BIT_WAKE_THS_W_XL_26 |
        ASM330LHH_WAKE_UP_DUR_BITS_SLEEP_DUR_DEFAULT |
        ASM330LHH_WAKE_UP_DUR_BITS_SLEEP_DUR_DEFAULT,

        ASM330LHH_FREE_FALL_ADDR |
        ASM330LHH_FREE_FALL_BITS_FF_DUR_4_0_DEFAULT |
        ASM330LHH_FREE_FALL_BITS_FF_THS_156_mg,

        ASM330LHH_MD1_CFG_ADDR |
        ASM330LHH_MD1_CFG_BIT_INT1_SLEEP_CHANGE_DISABLE |
        ASM330LHH_MD1_CFG_BIT_INT1_WU_DISABLE |
        ASM330LHH_MD1_CFG_BIT_INT1_FF_DISABLE |
        ASM330LHH_MD1_CFG_BIT_INT1_6D_DISABLE,

        ASM330LHH_MD2_CFG_ADDR |
        ASM330LHH_MD2_CFG_BIT_INT2_SLEEP_CHANGE_DISABLE |
        ASM330LHH_MD2_CFG_BIT_INT2_WU_DISABLE |
        ASM330LHH_MD2_CFG_BIT_INT2_FF_DISABLE |
        ASM330LHH_MD2_CFG_BIT_INT2_6D_DISABLE |
        ASM330LHH_MD2_CFG_BIT_INT2_TIMESTAMP_DISABLE,

        ASM330LHH_X_OFS_USR_ADDR |
        ASM330LHH_X_OFS_USR_BIT_X_OFS_USR_DEFAULT,

        ASM330LHH_Y_OFS_USR_ADDR |
        ASM330LHH_Y_OFS_USR_BIT_Y_OFS_USR_DEFAULT,

        ASM330LHH_Z_OFS_USR_ADDR |
        ASM330LHH_Z_OFS_USR_BIT_Z_OFS_USR_DEFAULT,




};



/*=======[I N T E R N A L   F U N C T I O N   D E C L A R A T I O N S]========*/

/*=======[E X T E R N A L   F U N C T I O N   D E C L A R A T I O N S]========*/

/*=======[E N D   O F   F I L E]==============================================*/

